// Generated by gencpp from file rail_manipulation_msgs/GraspFeedback.msg
// DO NOT EDIT!


#ifndef RAIL_MANIPULATION_MSGS_MESSAGE_GRASPFEEDBACK_H
#define RAIL_MANIPULATION_MSGS_MESSAGE_GRASPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rail_manipulation_msgs
{
template <class ContainerAllocator>
struct GraspFeedback_
{
  typedef GraspFeedback_<ContainerAllocator> Type;

  GraspFeedback_()
    : indices_considered()
    , index_selected(0)  {
    }
  GraspFeedback_(const ContainerAllocator& _alloc)
    : indices_considered(_alloc)
    , index_selected(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _indices_considered_type;
  _indices_considered_type indices_considered;

   typedef int32_t _index_selected_type;
  _index_selected_type index_selected;




  typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GraspFeedback_

typedef ::rail_manipulation_msgs::GraspFeedback_<std::allocator<void> > GraspFeedback;

typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspFeedback > GraspFeedbackPtr;
typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspFeedback const> GraspFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rail_manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rail_manipulation_msgs': ['/home/hcilab/Documents/jieru/NRI-authoring-Backend/src/rail_manipulation_msgs/msg', '/home/hcilab/Documents/jieru/NRI-authoring-Backend/devel/share/rail_manipulation_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e864dcbf0eb315180e735726b63001e";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e864dcbf0eb3151ULL;
  static const uint64_t static_value2 = 0x80e735726b63001eULL;
};

template<class ContainerAllocator>
struct DataType< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rail_manipulation_msgs/GraspFeedback";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] indices_considered           # indices of grasps seen by the user\n\
int32 index_selected                 # index of grasp selected for execution\n\
";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.indices_considered);
      stream.next(m.index_selected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rail_manipulation_msgs::GraspFeedback_<ContainerAllocator>& v)
  {
    s << indent << "indices_considered[]" << std::endl;
    for (size_t i = 0; i < v.indices_considered.size(); ++i)
    {
      s << indent << "  indices_considered[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.indices_considered[i]);
    }
    s << indent << "index_selected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index_selected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAIL_MANIPULATION_MSGS_MESSAGE_GRASPFEEDBACK_H
